name: aml_kaggle_chll
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pip
  - pip:
    # Core ML packages with exact versions
    - scikit-learn==1.5.1
    - pandas==2.2.2
    - jupyterlab==4.2.3
    - joblib==1.4.2
    - xgboost==2.1.0
    - hyperopt==0.2.7
    - lightgbm==4.4.0
    - lime==0.2.0.1
    - wandb==0.17.4
    
    # Additional packages needed for the src package
    - numpy
    - matplotlib
    - seaborn
    - python-dotenv
    
    # Development and utility packages
    - jupyter
    - ipykernel
    - notebook
    - loguru
    - tqdm
    - typer
    - pytest
    - ruff
    
    # Local package as editable install
    - -e .
