[project]
name = "aml_kaggle_chll"
description = "A short description of the project."
version = "0.1.0"
channels = ['conda-forge']
platforms = ['linux-64', 'osx-64', 'osx-arm64', 'win-64']

[dependencies]
python = "3.11.4"
loguru = "*"
pytest = "*"
ruff = "*"
tqdm = "*"
typer = "*"
pip = "*"

[pypi-dependencies]
# Core ML packages with exact versions
scikit-learn = "1.5.1"
pandas = "2.2.2"
jupyterlab = "4.2.3"
joblib = "1.4.2"
xgboost = "2.1.0"
hyperopt = "0.2.7"
lightgbm = "4.4.0"
lime = "0.2.0.1"
wandb = "0.17.4"

# Additional packages needed for the src package
numpy = "*"
matplotlib = "*"
seaborn = "*"
python-dotenv = "*"

# Development and utility packages
jupyter = "*"
ipykernel = "*"
notebook = "*"

# Local package as editable install
brayam-pineda-ml = { path = ".", editable = true }
