from setuptools import setup, find_packages

setup(
    name="brayam-pineda-ml",
    version="0.3.1",
    description="Machine Learning package for NBA draft prediction and weather forecasting using LightGBM and XGBoost",
    author="Brayam Alexander Pineda",
    author_email="brayam.pineda@student.uts.edu.au",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "scikit-learn==1.5.1",
        "pandas==2.2.2",
        "numpy>=1.24.0",
        "lightgbm==4.4.0",
        "joblib==1.4.2",
        "xgboost==2.1.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "hyperopt==0.2.7",
        "lime==0.2.0.1",
        "wandb==0.17.4",
        "loguru>=0.7.0",
        "tqdm>=4.65.0",
        "typer>=0.9.0",
        "python-dotenv>=1.0.0",
        "requests>=2.28.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Information Analysis",
    ],
)
